---
apiVersion: v1
kind: Service
metadata:
  name: rolloutService
  labels:
    app: color-deployment
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: color-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: rolloutService-preview
  labels:
    app: color-deployment
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: color-deployment
