---
apiVersion: v1
kind: Service
metadata:
  name: blue-deployment
  labels:
    app: color-deployment
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: color-deployment
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: green-deployment
#   labels:
#     app: color-deployment
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#   selector:
#     app: color-deployment
