apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.4.0
    helm:
      valueFiles:
      - $values/helm-values/prometheus/values.yaml
  - repoURL: 'https://github.com/vineet-007/examples.git'
    targetRevision: main
    ref: values 
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - ServerSideApply=true 
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true  