apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databases.custom-api.example.org
spec:
  group: custom-api.example.org
  names:
    kind: database
    plural: databases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  readCapacity:
                    type: integer
                    description: provisioned read capacity of the dynamoDB table
                  region:
                    type: string
                    description: region where the s3 bucket and dynamoDB table will be deployed
                required:
                  - readCapacity
                  - region
            required:
              - parameters
  # claimNames:
  #   kind: custom-database
  #   plural: custom-databases
