apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: example
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    engine: aurora-postgresql
    masterUsername: admin1
    masterPasswordSecretRef:
      name: sample-cluster-password
      namespace: crossplane-system
      key: password
    skipFinalSnapshot: true
    databaseName: auroradb
    dbClusterParameterGroupName: example
  writeConnectionSecretToRef:
    name: sample-rds-cluster-secret
    namespace: crossplane-system
  providerConfigRef:
    name: default    
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-cluster-password
  namespace: crossplane-system
type: Opaque
stringData:
  password: TestPass0!
